# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waggle', '0002_assessment_content_related'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessment',
            old_name='challenge_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='assessment',
            old_name='challenge_tests',
            new_name='tests',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='challenge_soln',
        ),
        migrations.AddField(
            model_name='assessment',
            name='soln',
            field=models.FileField(default='challengeXsoln', upload_to='solnFiles/'),
        ),
    ]
