# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waggle', '0007_auto_20160721_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='soln',
            field=models.FileField(default='challengeXsoln.py', upload_to=''),
        ),
    ]
