# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waggle', '0008_auto_20160721_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='soln',
            field=models.FileField(default='challengeXsoln.py', upload_to='/Users/smeo/django_waggle/mysite/waggle/solnFiles/'),
        ),
    ]
