# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waggle', '0009_auto_20160721_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='tests',
        ),
    ]
