# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 19:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waggle', '0012_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='gmail',
        ),
    ]
