# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waggle', '0016_auto_20160803_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ManyToManyField(to='waggle.Course'),
        ),
    ]
