# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 21:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waggle', '0017_auto_20160803_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
    ]
