# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waggle', '0019_auto_20160803_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='course',
            field=models.ManyToManyField(to='waggle.Course'),
        ),
    ]
