# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 22:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waggle', '0020_studentprofile_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waggle.Course')),
            ],
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='course',
        ),
        migrations.AddField(
            model_name='progress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waggle.StudentProfile'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='usr_progress',
            field=models.ManyToManyField(through='waggle.Progress', to='waggle.Course'),
        ),
    ]
