# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 06:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waggle', '0024_auto_20160803_2346'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='waggle.Module')),
            ],
        ),
        migrations.RemoveField(
            model_name='courseprogress',
            name='course',
        ),
        migrations.RemoveField(
            model_name='courseprogress',
            name='student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='course_progress',
        ),
        migrations.AddField(
            model_name='student',
            name='user_courses',
            field=models.ManyToManyField(to='waggle.Course'),
        ),
        migrations.DeleteModel(
            name='CourseProgress',
        ),
        migrations.AddField(
            model_name='moduleprogress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waggle.Student'),
        ),
        migrations.AddField(
            model_name='student',
            name='module_progress',
            field=models.ManyToManyField(through='waggle.ModuleProgress', to='waggle.Module'),
        ),
    ]
