# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waggle', '0027_auto_20160804_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
