# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waggle', '0029_auto_20160805_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='ipython_notebooks',
        ),
        migrations.RemoveField(
            model_name='content',
            name='videos',
        ),
        migrations.AddField(
            model_name='content',
            name='ipython_notebook',
            field=models.FileField(null=True, upload_to='/waggle/assesment/content/notebooks/'),
        ),
        migrations.AddField(
            model_name='content',
            name='video',
            field=models.FileField(null=True, upload_to='/waggle/assessment/content/videos/'),
        ),
    ]
