# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-11 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import waggle.models


class Migration(migrations.Migration):

    dependencies = [
        ('waggle', '0032_auto_20160810_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='soln',
        ),
        migrations.AddField(
            model_name='assessment',
            name='assess_file',
            field=models.FileField(null=True, upload_to=waggle.models.assessment_directory_path),
        ),
        migrations.AlterField(
            model_name='content',
            name='ipython_notebook',
            field=models.FileField(null=True, upload_to=waggle.models.notebook_directory_path),
        ),
        migrations.AlterField(
            model_name='content',
            name='video',
            field=models.FileField(null=True, upload_to=waggle.models.video_directory_path),
        ),
    ]
