# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-11 23:25
from __future__ import unicode_literals

from django.db import migrations, models
import waggle.models


class Migration(migrations.Migration):

    dependencies = [
        ('waggle', '0033_auto_20160811_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='html_notebook',
            field=models.FileField(null=True, upload_to=waggle.models.notebook_directory_path),
        ),
    ]
