# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-12 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waggle', '0034_content_html_notebook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentprogress',
            name='submission_feedback',
        ),
        migrations.AddField(
            model_name='assessmentprogress',
            name='error_name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='assessmentprogress',
            name='long_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='assessmentprogress',
            name='short_description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='assessmentprogress',
            name='code_submission',
            field=models.TextField(default='#Type python code here'),
        ),
    ]
