# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-16 05:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waggle', '0038_auto_20160812_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessmentprogress',
            old_name='error_name',
            new_name='errors_list',
        ),
        migrations.RemoveField(
            model_name='assessmentprogress',
            name='long_description',
        ),
        migrations.RemoveField(
            model_name='assessmentprogress',
            name='short_description',
        ),
    ]
