# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-18 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import waggle.models


class Migration(migrations.Migration):

    dependencies = [
        ('waggle', '0039_auto_20160815_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='ipython_notebook',
        ),
        migrations.AddField(
            model_name='assessment',
            name='order',
            field=models.PositiveSmallIntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='module',
            name='order',
            field=models.PositiveSmallIntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=waggle.models.video_directory_path),
        ),
    ]
