# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-18 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waggle', '0040_auto_20160818_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='order',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='order',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
