# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-18 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waggle', '0041_auto_20160818_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentprogress',
            name='assessment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='waggle.Assessment'),
        ),
        migrations.AlterField(
            model_name='contentprogress',
            name='content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='waggle.Content'),
        ),
        migrations.AlterField(
            model_name='courseprogress',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='waggle.Course'),
        ),
        migrations.AlterField(
            model_name='moduleprogress',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='waggle.Module'),
        ),
    ]
