# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-21 16:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import waggle.models


class Migration(migrations.Migration):

    dependencies = [
        ('waggle', '0042_auto_20160818_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to=waggle.models.video_directory_path)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='waggle.Module')),
            ],
        ),
        migrations.CreateModel(
            name='VideoProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_notes', models.TextField(null=True)),
                ('video_timepoint', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='contentprogress',
            name='content',
        ),
        migrations.RemoveField(
            model_name='contentprogress',
            name='student',
        ),
        migrations.RemoveField(
            model_name='content',
            name='video',
        ),
        migrations.RemoveField(
            model_name='student',
            name='content_progress',
        ),
        migrations.AddField(
            model_name='content',
            name='title',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='related',
            name='title',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='ContentProgress',
        ),
        migrations.AddField(
            model_name='videoprogress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waggle.Student'),
        ),
        migrations.AddField(
            model_name='videoprogress',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='waggle.Video'),
        ),
        migrations.AddField(
            model_name='student',
            name='video_progress',
            field=models.ManyToManyField(through='waggle.VideoProgress', to='waggle.Video'),
        ),
    ]
