# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-24 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waggle', '0044_auto_20160821_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video',
        ),
        migrations.AddField(
            model_name='video',
            name='video_URL',
            field=models.URLField(null=True),
        ),
    ]
