# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-24 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import waggle.models


class Migration(migrations.Migration):

    dependencies = [
        ('waggle', '0045_auto_20160824_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='related',
            name='links',
        ),
        migrations.AddField(
            model_name='related',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='related',
            name='notebook',
            field=models.FileField(blank=True, null=True, upload_to=waggle.models.notebook_directory_path),
        ),
        migrations.AddField(
            model_name='related',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='related',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
