# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-26 16:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waggle', '0047_assessment_code_editor_filler'),
    ]

    operations = [
        migrations.RenameField(
            model_name='related',
            old_name='text',
            new_name='description',
        ),
    ]
