# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-26 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waggle', '0048_auto_20160826_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentprogress',
            name='code_submission',
            field=models.TextField(default='#Type python code below'),
        ),
    ]
