# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-30 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waggle', '0050_auto_20160830_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseprogress',
            name='date_enrolled',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
