# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-31 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waggle', '0051_auto_20160830_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleprogress',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
