# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-06 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waggle', '0058_auto_20160903_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicks_on_content_tab_counter', models.PositiveSmallIntegerField(default=0)),
                ('content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='waggle.Content')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='waggle.Student')),
            ],
        ),
        migrations.AddField(
            model_name='videoprogress',
            name='clicks_on_video_open_counter',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='content_progress',
            field=models.ManyToManyField(through='waggle.ContentProgress', to='waggle.Content'),
        ),
    ]
