# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-07 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import waggle.models


class Migration(migrations.Migration):

    dependencies = [
        ('waggle', '0061_auto_20160907_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=waggle.models.assessment_image_directory_path),
        ),
    ]
