# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-07 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waggle', '0062_assessment_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentsubmission',
            name='assessmentprogresses',
        ),
        migrations.AddField(
            model_name='assessmentsubmission',
            name='assessmentprogresses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='waggle.AssessmentProgress'),
        ),
    ]
