# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_description', models.TextField()),
                ('challenge_soln', models.TextField()),
                ('challenge_tests', models.TextField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Module')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipython_notebooks', models.FilePathField(path='/main/assesment/content/notebooks/')),
                ('videos', models.FilePathField(path='/main/assessment/content/videos/')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Module')),
            ],
        ),
        migrations.CreateModel(
            name='Related',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('links', models.TextField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Module')),
            ],
        ),
    ]
