# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20160721_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='soln',
            field=models.FilePathField(),
        ),
    ]
