# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_assessment_tests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='soln',
            field=models.FileField(default='challenge1soln_DCR6J7d.py', upload_to='/home/smccumsey/main-classroom//main/solnFiles/'),
        ),
    ]
