# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_student_gmail'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.Course'),
            preserve_default=False,
        ),
    ]
