# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20160810_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='ipython_notebook',
            field=models.FilePathField(null=True, path='main/static/notebooks/'),
        ),
        migrations.AlterField(
            model_name='content',
            name='video',
            field=models.FilePathField(null=True, path='main/static/video/'),
        ),
    ]
