# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-12 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20160811_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentprogress',
            name='video_timepoint',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
