# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-12 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20160812_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentprogress',
            name='notebook_download_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contentprogress',
            name='video_notes',
            field=models.TextField(null=True),
        ),
    ]
