# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-13 05:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_auto_20160812_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentprogress',
            name='assessment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Assessment', unique=True),
        ),
        migrations.AlterField(
            model_name='contentprogress',
            name='content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Content', unique=True),
        ),
        migrations.AlterField(
            model_name='courseprogress',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Course', unique=True),
        ),
        migrations.AlterField(
            model_name='moduleprogress',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Module', unique=True),
        ),
    ]
