# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-21 18:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_auto_20160821_0938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='name',
            new_name='title',
        ),
    ]
