# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-24 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_auto_20160824_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='code_editor_filler',
            field=models.TextField(null=True),
        ),
    ]
