# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-01 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_auto_20160901_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionrecord',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submissionrecord',
            name='record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.AssessmentProgress'),
        ),
    ]
