# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-02 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_auto_20160901_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissionrecord',
            name='record',
        ),
        migrations.AlterField(
            model_name='assessmentprogress',
            name='code_submission',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='SubmissionRecord',
        ),
    ]
