# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-02 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_auto_20160902_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentprogress',
            name='attempted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessmentprogress',
            name='number_of_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assessmentprogress',
            name='solved',
            field=models.BooleanField(default=False),
        ),
    ]
