# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-07 18:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_assessmentsubission'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssessmentSubission',
            new_name='AssessmentSubmission',
        ),
    ]
